version: '3.1'

services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: SIM,
      POSTGRES_USER: postgres,
    ports:
      - "5432:5432"
