version: '3.1'

services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: SIM
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
