version: '3.1'

services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: SIM
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  api_migrate:
    build: .
    image: api
    command: python manage.py migrate --settings=SIM.docker
    depends_on:
      - db

  api:
      image: api
      command: python manage.py runserver 0.0.0.0:8000 --settings=SIM.docker
      ports:
        - "8000:8000"
      depends_on:
        - db
        - api_migrate