# Generated by Django 2.2.2 on 2019-06-14 15:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigma_PG', models.DecimalField(decimal_places=5, max_digits=7)),
                ('sigma_MG', models.DecimalField(decimal_places=5, max_digits=7)),
                ('sigma_S', models.DecimalField(decimal_places=5, max_digits=7)),
                ('mean_PG', models.DecimalField(decimal_places=5, max_digits=7)),
                ('mean_MG', models.DecimalField(decimal_places=5, max_digits=7)),
                ('mean_S', models.DecimalField(decimal_places=5, max_digits=7)),
                ('alpha_A', models.DecimalField(decimal_places=5, max_digits=7)),
                ('beta_A', models.DecimalField(decimal_places=5, max_digits=7)),
                ('n_cranes', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('mean_time', models.DecimalField(decimal_places=5, max_digits=7)),
                ('percent_trucks_in_queue', models.DecimalField(decimal_places=5, max_digits=7)),
                ('max_time_in_queue', models.IntegerField()),
                ('n_trucks_in_queue', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
        ),
    ]
