# Generated by Django 2.2.2 on 2019-06-14 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20190614_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationmodel',
            name='n_trucks_in_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, default=0, null=True, size=None),
        ),
    ]
