# Generated by Django 2.2.2 on 2019-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_auto_20190614_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationmodel',
            name='n_trucks_in_queue',
            field=models.TextField(),
        ),
    ]
