# Generated by Django 2.2.2 on 2019-06-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_auto_20190614_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationmodel',
            old_name='max_time',
            new_name='seed',
        ),
    ]
